### ISSUE TITLE
Translation file not up to date

### ISSUE THREAD

**Issue by imranMnts** [tink-ab/tink-money-manager-ios#81]
According to your [documentation](https://github.com/tink-ab/tink-money-manager-ios/blob/master/LOCALIZABLE_STRINGS.md), we can refer to the [TinkMoneyManagerUI.strings](https://github.com/tink-ab/tink-money-manager-ios/blob/master/en.xcloc/Source%20Contents/Sources/TinkMoneyManagerUI/en.lproj/TinkMoneyManagerUI.strings) file that we can find in the repository but some items have not been added.

Eg. `Overview.Accounts.All`, mentioned in the documentation, used by the SDK but not added in the strings file.

Can you have a look and add the missing keys to align documentation and avoid any trouble on our side please

**Comment by belous** [comment]
Hi @imranMnts! Thank you for noticing this. Indeed, the `.string`-file has not been updated apparently.
But the [LOCALIZABLE_STRINGS.md](https://github.com/tink-ab/tink-money-manager-ios/blob/master/LOCALIZABLE_STRINGS.md) you mention is up-to-dated.
Now we have updated the `en.xcloc` folder as well: https://github.com/tink-ab/tink-money-manager-ios/pull/82

**Comment by imranMnts** [comment]
Thanks a lot 🙏🏼
