### ISSUE TITLE
Xcode15.X- error: Multiple commands produce "Assets.car"

### ISSUE THREAD

**Issue by odemolliens** [tink-ab/tink-money-manager-ios#86]
During build phase:

`error: Multiple commands produce '/Users/builder/Library/Developer/Xcode/DerivedData/xxx/xxx.app/Assets.car'`

[Assets.car](https://github.com/tink-ab/tink-money-manager-ios/blob/master/TinkMoneyManagerUI.xcframework/ios-arm64/TinkMoneyManagerUI.framework/Assets.car) file name is too generic.

When you have any other third party (like GoogleMaps) using same file name, you aren't able to compile the project anymore.
![Screenshot 2024-04-24 at 09 10 37](https://github.com/tink-ab/tink-money-manager-ios/assets/2726958/22db446a-f1f4-483e-83db-1d783d55b97f)

Please rename `Assets.car` to `TinkAssets.car` by eg

**Comment by odemolliens** [comment]
I noticed that other libraries having an `Assets.car` are all packaged in a bundle first (and so no build issue because no conflict on path)

Eg with Instabug: https:/github.com/Instabug/Instabug-iOS/releases/download/13.0.0/Instabug-XCFramework.zip

![Screenshot 2024-04-25 at 08 53 17](https://github.com/tink-ab/tink-money-manager-ios/assets/2726958/dc00c06a-ed4b-4656-84b0-fd5707af1c31)


![Screenshot 2024-04-25 at 08 53 25](https://github.com/tink-ab/tink-money-manager-ios/assets/2726958/25fdad11-5f83-4b8e-acc5-0a540fba977c)

**Comment by belous** [comment]
Hi @odemolliens! Thank you for noticing it. We are going to fix it in the further releases.
But for now please change the integration by using one of the workarounds (you can find them [here](https://dev.to/kylefoo/xcode-12-new-build-system-warns-multiple-commands-produce-assets-car-56im)).

**Comment by belous** [comment]
Hi! Thank you very much again for reporting this.
We have moved the Assets catalog to the separate bundle in our recent release.
You can check it here: https://github.com/tink-ab/tink-money-manager-ios/releases/tag/1.3.2
